// Mocks generated by Mockito 5.4.6 from annotations
// in view_shell/test/prop_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

import 'prop_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [Callbacks].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallbacks extends _i1.Mock implements _i2.Callbacks {
  MockCallbacks() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> futureSuccess() =>
      (super.noSuchMethod(
            Invocation.method(#futureSuccess, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#futureSuccess, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> futureFailure() =>
      (super.noSuchMethod(
            Invocation.method(#futureFailure, []),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#futureFailure, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  String syncSuccess() =>
      (super.noSuchMethod(
            Invocation.method(#syncSuccess, []),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#syncSuccess, []),
            ),
          )
          as String);

  @override
  String syncFailure() =>
      (super.noSuchMethod(
            Invocation.method(#syncFailure, []),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#syncFailure, []),
            ),
          )
          as String);

  @override
  void onSucces(dynamic value) => super.noSuchMethod(
    Invocation.method(#onSucces, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void onFailure(Object? error, StackTrace? st) => super.noSuchMethod(
    Invocation.method(#onFailure, [error, st]),
    returnValueForMissingStub: null,
  );
}
